version: 2
models:
  - name: stg_claims
    columns:
      - name: claim_id
        tests: [not_null, unique]
  - name: fct_claim_performance
    columns:
      - name: claim_id
        tests: [not_null]
